version: '2.2'

services:

  waldur-mastermind-worker_init:
    image: 'opennode/waldur-mastermind:latest'
    networks:
      - waldur
    environment:
      - GLOBAL_SECRET_KEY
      - POSTGRESQL_PASSWORD
    depends_on:
      waldur-db:
        condition: service_healthy
    command: initdb createadmin

  # Redis
  waldur-queue_init:
    image: 'bitnami/redis:latest'
    networks:
      - waldur
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'waldur_queue:/bitnami'
    command: bash -c "sed -i 's/^protected-mode yes/protected-mode no/g' /bitnami/redis/conf/redis.conf"
