version: '2.2'

services:

  waldur-mastermind-worker_init:
    image: 'opennode/waldur-mastermind:latest'
    networks:
      - waldur
    environment:
      - GLOBAL_SECRET_KEY
      - POSTGRESQL_PASSWORD
    depends_on:
      waldur-db:
        condition: service_healthy
    command: waldur migrate --noinput
